out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: False
  project: scratch  # W&B project for debugging runs.
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_num_types: 4
  edge_encoder_bn: False
pretrained:
  dir: /network/scratch/l/lavoiems/graphgps/pretrained/pcqm4m-GPS+RWSE.deep
  reset_prediction_head: True
  freeze_main: False
sem:
  L: 64
  V: 16
  tau: 1.0
train:
  mode: custom
  batch_size: 32
model:
  type: GPSModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gnn:
  head: san_graph
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  batchnorm: True
  act: gelu
  dropout: 0.0
  agg: mean
optim:
  base_lr: 0.001
  num_iteration: 5
